import { Brand, BrandStatus } from "../data/types";

export const Brands: Array<Brand> = [
  {
    title: 'classifyPerfect.ai',
    url: 'https://classifyPerfect.ai',
    logo: '/svg/classifyPerfect.svg',
    icon: '/svg/classifyPerfect-icon.svg',
    status: BrandStatus.COMING_SOON,
    primary: "#ffd900",
  },
  {
    title: 'contentPerfect.ai',
    url: 'https://contentPerfect.ai',
    logo: '/svg/contentPerfect.svg',
    icon: '/svg/contentPerfect-icon.svg',
    status: BrandStatus.LIVE,
    summary: "contentPerfect.AI leverages AI to deliver SEO-optimized content plans and calculated blog posts, boosting site traffic with data-driven strategies designed by SEO experts.",
    primary: "#D14124",
    stagingUrl: "https://content-perfect-theta.vercel.app/",
    developmentUrl: "https://content-perfect-git-development-loud-interactives-projects.vercel.app/"
  },
  {
    title: 'factcheckPerfect.ai',
    url: 'https://factcheckPerfect.ai',
    logo: '/svg/factcheckPerfect.svg',
    icon: '/svg/factcheckPerfect-icon.svg',
    status: BrandStatus.LIVE,
    primary: "#179BAE",
    stagingUrl: "https://factchecker-perfect.vercel.app/",
    developmentUrl: "https://factchecker-perfect-git-development-loud-interactives-projects.vercel.app/",
    summary: "factcheckPerfect.ai helps businesses verify their articles and content for accuracy and credibility using AI."
  },
  {
    title: 'imagePerfect.ai',
    url: 'https://imagePerfect.ai',
    logo: '/svg/imagePerfect.svg',
    icon: '/svg/imagePerfect-icon.svg',
    status: BrandStatus.COMING_SOON,
    summary: "Perfect image file names, alt text, image captions, and keyphrases for the document management system using AI.",
    primary: "#EF476F",
  },
  {
    title: 'indexPerfect.ai',
    url: 'https://indexPerfect.ai',
    logo: '/svg/indexPerfect.svg',
    icon: '/svg/indexPerfect-icon.svg',
    status: BrandStatus.LIVE,
    summary: "indexPerfect.ai helps businesses identify the effectiveness of their website's indexation using AI.",
    primary: "#f59f3c",
    stagingUrl: "https://index-perfect.vercel.app/",
    developmentUrl: "https://index-perfect-git-development-loud-interactives-projects.vercel.app"
  },
  {
    title: 'pagePerfect.ai',
    summary: "Remove the guesswork and harness the power of AI for your SEO content. pagePerfect generates effective, optimized content that you simply copy and paste onto your website.",
    url: 'https://pagePerfect.ai',
    logo: '/svg/pagePerfect.svg',
    icon: '/svg/pagePerfect-icon.svg',
    status: BrandStatus.LIVE,
    primary: "#666699",
    stagingUrl: "https://page-perfect-one.vercel.app/",
    developmentUrl: "https://page-perfect-git-development-loud-interactives-projects.vercel.app/"
  },
  {
    title: 'SEOPerfect.ai',
    url: 'https://SEOPerfect.ai',
    logo: '/svg/SEOPerfect.svg',
    icon: '/svg/SEOPerfect-icon.svg',
    status: BrandStatus.MASTER,
    stagingUrl: "https://perfect-seo.vercel.app/",
    developmentUrl: "https://perfect-seo-git-development-loud-interactives-projects.vercel.app/",
    primary: "#E63946",
    summary: "Maximize your marketing and SEO with AI-generated content of human-like excellence!"
  },
  {
    title: 'preferencesPerfect.ai',
    url: 'https://preferencesPerfect.ai',
    logo: '/svg/preferencesPerfect.svg',
    icon: '/svg/preferencesPerfect-icon.svg',
    status: BrandStatus.LIVE,
    primary: "#9dc450",
    summary: "preferencesPerfect allows you to update all your brand information across our AI suite all in one place.",
    stagingUrl: "https://preferences-perfect.vercel.app/",
    developmentUrl: "https://preferences-perfect-git-development-loud-interactives-projects.vercel.app/"
  },
  {
    title: 'schemaPerfect.ai',
    url: 'https://schemaPerfect.ai',
    logo: '/svg/schemaPerfect.svg',
    icon: '/svg/schemaPerfect-icon.svg',
    summary: "schemaPerfect.ai uses advanced AI to automatically generate accurate and comprehensive JSON-LD schemas for any web page, improving your SEO and structured data implementation.",
    status: BrandStatus.COMING_SOON,
    primary: "#235789",
  },
  {
    title: 'editPerfect.ai',
    url: 'https://editPerfect.ai',
    logo: '/svg/editPerfect.svg',
    icon: '/svg/editPerfect-icon.svg',
    // summary: "Perfect your e-commerce product pages with more detailed product descriptions, features, specifications, and product information using AI.",
    status: BrandStatus.COMING_SOON,
    primary: "#235789",
  },
  {
    title: 'productPerfect.ai',
    url: 'https://productPerfect.ai',
    logo: '/svg/productPerfect.svg',
    icon: '/svg/productPerfect-icon.svg',
    // summary: "Perfect your e-commerce product pages with more detailed product descriptions, features, specifications, and product information using AI.",
    summary: "        Transform any product page into comprehensive, structured data with our advanced AI-powered scraping technology.",
    status: BrandStatus.COMING_SOON,
    primary: "#235789",
  },
  {
    title: 'redirectPerfect.ai',
    url: 'https://redirectPerfect.ai',
    logo: '/svg/redirectPerfect.svg',
    icon: '/svg/redirectPerfect-icon.svg',
    status: BrandStatus.PLANNED,
    primary: "#999948",
  },
  {
    title: 'socialPerfect.ai',
    url: 'https://socialPerfect.ai',
    logo: '/svg/socialPerfect.svg',
    icon: '/svg/socialPerfect-icon.svg',
    status: BrandStatus.LIVE,
    summary: "Amplify your social media engagement by generating the right emoticon and hashtags to achieve the right tone",
    stagingUrl: "https://social-perfect.vercel.app/",
    developmentUrl: "https://social-perfect-git-development-loud-interactives-projects.vercel.app/",
    primary: "#CC6699"
  },
  {
    title: 'synopsisPerfect.ai',
    url: 'https://synopsisPerfect.ai',
    logo: '/svg/synopsisPerfect.svg',
    icon: '/svg/synopsisPerfect-icon.svg',
    status: BrandStatus.LIVE,
    primary: "#8b59ad",
    stagingUrl: "https://synopsis-perfect.vercel.app/",
    developmentUrl: "https://synopsis-perfect-git-development-loud-interactives-projects.vercel.app/",
    summary: "synopsisPerfect.ai helps businesses identify their brand and the effectiveness of information conveyed on their website using AI."
  },
  {
    title: 'voicePerfect.ai',
    url: 'https://voicePerfect.ai',
    logo: '/svg/voicePerfect.svg',
    icon: '/svg/voicePerfect-icon.svg',
    status: BrandStatus.LIVE,
    summary: "voicePerfect AI provides insights into the ideal tone, language style, common phrases, and inclusivity of your brand voice to perfect it in the minds of your customers.",
    stagingUrl: "https://voice-perfect.vercel.app/",
    developmentUrl: "https://voice-perfect-git-development-loud-interactives-projects.vercel.app/",
    primary: "#6699cc"
  }
];
